color: null
fieldLayouts:
  26675462-fb96-4d23-b93d-c7b18855d8d4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-12T12:54:15+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bf0560dd-c10e-4147-bb21-33b6e743427e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-19T14:43:15+00:00'
            elementCondition: null
            fieldUid: b0051ca7-90f1-401f-91f8-01488af83488 # art
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a1a8287f-6a61-4e18-bc13-2c9097ae3df0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-19T14:43:38+00:00'
            elementCondition: null
            fieldUid: 16df0a23-d742-4ad8-b1f9-338dce5f607a # img
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f433900-7c44-450c-b251-a75eabfd0409
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-12T12:56:29+00:00'
            elementCondition: null
            fieldUid: f7d085ff-ca17-4634-af22-21ab371bb1b9 # action
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 20a36bfc-38f6-49c1-938b-0b5f0659a214
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-12T12:56:29+00:00'
            elementCondition: null
            fieldUid: a543327e-8cfc-4c29-b047-b12cf81f111c # gensAdmin
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 458f872e-d4ee-4012-a57f-680dc9ac63ab
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 05ed4f4c-0b4b-4848-9622-dd5458cc5ae0
        userCondition: null
handle: article
hasTitleField: true
icon: null
name: article
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
