color: null
fieldLayouts:
  6214ee96-c3fc-4c72-a198-4498cf346582:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-20T17:45:57+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e5251e04-d351-41d7-ba92-f98836366fa9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-20T19:44:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b6d36efd-b595-4b9b-9366-497092d09733 # dt
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ead8b5ca-5636-430d-b85e-c815f33f3d31
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-20T17:48:36+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f7d085ff-ca17-4634-af22-21ab371bb1b9 # action
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca1efc4e-98ac-4452-aa50-7b9d3b50ed35
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-20T17:48:36+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 61e4ba75-3c17-4a7f-acc6-322b97ee9528 # gens
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 38329450-8066-4e70-a195-058f22bbd1cd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-07T23:55:11+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b4a6c2b9-87db-4f20-8133-1ca8cde42796 # obj
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b9b5abdd-050f-458d-bc48-9fe30fd6387f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9ec9d449-5b25-4a20-92d6-4366d518115e
        userCondition: null
handle: inscrit
hasTitleField: true
icon: null
name: inscrit
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
