color: null
fieldLayouts:
  b63ca111-a5c8-467a-9b31-b969383bc41f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-12T12:58:33+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e3308971-4e65-4925-83eb-f4f7014f0683
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-12T13:01:09+00:00'
            elementCondition: null
            fieldUid: 61e4ba75-3c17-4a7f-acc6-322b97ee9528 # gens
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f08d1a2-6f6a-47a6-adf2-c40b8f401b24
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-12T13:01:09+00:00'
            elementCondition: null
            fieldUid: ec1ad995-5e56-42ce-b5f1-c47f311664ca # tag
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b16e4c7e-5d67-43b5-919b-48366a157f48
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 95fd643d-d37c-47ce-8b50-11cc56b0912a
        userCondition: null
handle: msg
hasTitleField: true
icon: null
name: msg
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
