color: null
fieldLayouts:
  2e9c0df6-ff74-4183-b11d-8fd23ce50217:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-30T02:49:29+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8cda4a06-83b0-4020-92a7-49339436db37
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-30T02:52:06+00:00'
            elementCondition: null
            fieldUid: bd1d9f29-cc92-44e1-9fc4-44eb474992cf # imgpilote
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2c5286a1-53c9-4798-a29a-9d1fb3333af0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-30T02:52:06+00:00'
            elementCondition: null
            fieldUid: 1dbdb624-0e6e-4f1a-b048-5aed379070c7 # nom
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a1652278-2b93-43d9-8242-27f194148cc3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-30T02:53:57+00:00'
            elementCondition: null
            fieldUid: f292de92-c1b2-45c5-8734-0371f823f9cb # voitures
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28556af4-1573-4470-b869-a02367700d82
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 35f388e0-67e5-4236-9b8f-c967893fc024
        userCondition: null
handle: pilotes
hasTitleField: true
icon: null
name: pilotes
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
