defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: f3a6590e-f320-4ab4-afd7-dfd64fdb04a3 # abo
handle: abo
maxAuthors: 1
name: Abo
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  03e942c5-fa2f-4d2a-b7e5-52766f07b3b2: # a
    enabledByDefault: true
    hasUrls: true
    template: abo/_entry.twig
    uriFormat: 'abo/{slug}'
  a7c10eaa-616c-4edf-8aa6-2ddc2e17d921: # agendafriends
    enabledByDefault: true
    hasUrls: true
    template: abo/_entry.twig
    uriFormat: 'abo/{slug}'
type: channel
