defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 21ec364a-a805-4314-866b-c93a3e80c3d6 # action
handle: action
maxAuthors: 1
name: Action
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  03e942c5-fa2f-4d2a-b7e5-52766f07b3b2: # a
    enabledByDefault: true
    hasUrls: true
    template: action/_entry.twig
    uriFormat: 'action/{slug}'
  a7c10eaa-616c-4edf-8aa6-2ddc2e17d921: # agendafriends
    enabledByDefault: true
    hasUrls: true
    template: action/_entry.twig
    uriFormat: 'action/{slug}'
type: channel
