defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 7a37312f-948f-4444-b01a-fdc18741916a # blog
handle: blog
maxAuthors: 1
name: Blog
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  03e942c5-fa2f-4d2a-b7e5-52766f07b3b2: # a
    enabledByDefault: true
    hasUrls: true
    template: blog/_entry.twig
    uriFormat: 'blog/{slug}'
  a7c10eaa-616c-4edf-8aa6-2ddc2e17d921: # agendafriends
    enabledByDefault: true
    hasUrls: true
    template: blog/_entry.twig
    uriFormat: 'blog/{slug}'
type: channel
