defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 953caa55-af63-4903-acfb-f73a70f54780 # desc
handle: desc
maxAuthors: 1
name: Desc
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  03e942c5-fa2f-4d2a-b7e5-52766f07b3b2: # a
    enabledByDefault: true
    hasUrls: true
    template: desc/_entry.twig
    uriFormat: 'desc/{slug}'
  a7c10eaa-616c-4edf-8aa6-2ddc2e17d921: # agendafriends
    enabledByDefault: true
    hasUrls: true
    template: desc/_entry.twig
    uriFormat: 'desc/{slug}'
  d1c448cf-2bc2-42c7-95e7-4ce5a5e67575: # routine
    enabledByDefault: true
    hasUrls: true
    template: desc/_entry.twig
    uriFormat: 'desc/{slug}'
type: channel
