defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: c3f3fb56-9fb3-4129-838b-1a5e7f05bc32 # gens
handle: gens
maxAuthors: 1
name: gens
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  03e942c5-fa2f-4d2a-b7e5-52766f07b3b2: # a
    enabledByDefault: true
    hasUrls: true
    template: gens/_entry.twig
    uriFormat: 'gens/{slug}'
  a7c10eaa-616c-4edf-8aa6-2ddc2e17d921: # agendafriends
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
