defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 655867ba-9aa7-4743-8a08-14f13af820fd # groupe
handle: groupe
maxAuthors: 1
name: Groupe
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  03e942c5-fa2f-4d2a-b7e5-52766f07b3b2: # a
    enabledByDefault: true
    hasUrls: true
    template: groupe/_entry.twig
    uriFormat: 'groupe/{slug}'
  a7c10eaa-616c-4edf-8aa6-2ddc2e17d921: # agendafriends
    enabledByDefault: true
    hasUrls: true
    template: groupe/_entry.twig
    uriFormat: 'groupe/{slug}'
type: channel
