defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 039b7336-79fe-4044-b756-5bf523a22f3e # Moment
handle: moment
maxAuthors: 1
name: Moment
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  03e942c5-fa2f-4d2a-b7e5-52766f07b3b2: # a
    enabledByDefault: true
    hasUrls: true
    template: moment/_entry.twig
    uriFormat: 'moment/{slug}'
  a7c10eaa-616c-4edf-8aa6-2ddc2e17d921: # agendafriends
    enabledByDefault: true
    hasUrls: true
    template: moment/_entry.twig
    uriFormat: 'moment/{slug}'
type: channel
