defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 64e8911c-d1b5-497c-b7ca-5479761cbe6f # msg
handle: msg
maxAuthors: 1
name: Msg
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  03e942c5-fa2f-4d2a-b7e5-52766f07b3b2: # a
    enabledByDefault: true
    hasUrls: true
    template: msg/_entry.twig
    uriFormat: 'msg/{slug}'
  a7c10eaa-616c-4edf-8aa6-2ddc2e17d921: # agendafriends
    enabledByDefault: true
    hasUrls: true
    template: msg/_entry.twig
    uriFormat: 'msg/{slug}'
type: channel
