dateModified: 1743291892
email:
  fromEmail: aluligu@gmail.com
  fromName: a
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    03e942c5-fa2f-4d2a-b7e5-52766f07b3b2: a # a
    8a6cd0b3-d0ff-4c2b-9142-ff50b5cf8a16: a # a
    9b987a32-67f0-4c54-920b-73bf016c0372: photoVoiture # photoVoiture
    59aacfcf-933c-4521-a3c9-e25dff69e354: Annee # Annee
    412d2b65-92f7-40dc-8dbf-e495840944c4: 'Voitures standard' # Voitures standard
    879ed238-6c41-49ca-bb35-e156a0f6b56a: Voitures # Voitures
    e5131bdd-7b21-4287-992b-d2504987a1a6: Marque # Marque
system:
  edition: solo
  live: true
  name: a
  schemaVersion: 5.6.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
