isPublic: true
name: 'Public Schema'
scope:
  - 'sites.a7c10eaa-616c-4edf-8aa6-2ddc2e17d921:read' # agendafriends
  - 'elements.drafts:read'
  - 'elements.revisions:read'
  - 'elements.inactive:read'
  - 'sections.9434ca7d-d978-4b3e-b98c-e00e8c4aedaf:read' # gens
  - 'volumes.0d874f90-596b-4955-b5f0-c6c493421528:read' # imgsvol
