altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  110bdf69-7d2d-49b3-b656-8377769866b9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-30T01:38:56+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 301fcc09-e30e-42c8-a093-6229cadc547f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a68822d8-8631-44d1-8f39-75fc4d21a1c7
        userCondition: null
fs: imgs
handle: imgsvol
name: imgsvol
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
